# .github/actions/apply/action.yml

name: apply

description: Terraform Apply Steps

runs:
  using: composite

  steps:

    - name: Common Before
      uses: ./.github/actions/common-before

    - name: Common Init
      uses: ./.github/actions/common-init

    - name: Check Plan Changed
      shell: bash
      run: |
        echo "***** Check Plan Changed *****"
        echo "plan-changed=$(cat plan-changed.txt)" >> "$GITHUB_ENV"
        cat plan-changed.txt

    - name: Terraform Apply
      if: env.plan-changed == 'true'
      shell: bash
      run: |
        echo "***** Terraform Apply *****"
        terraform apply \
          -input=false \
          "${tfEnvironment}-${tfRegion}-tfplan"
