# .github/config/2-applyParameters.yml

hub-uks:
  # Azure
  azureClientId:         '28412c13-5870-49c8-9777-0efe0fab6510'
  azureSubscriptionId:   '2bc7b65e-18d6-42ae-afb2-e66d50be6b05'
  azureTenantId:         '73578441-dc3d-4ecd-a298-fc5c6f40e191'
  # Terraform
  tfEnvironment:         'hub'
  tfRegion:              'uks'
  tfStateResourceGroup:  'rg-hub-uks-01'
  tfStateStorageAccount: 'sardzhubukstfstate'
  tfStateContainerName:  'iac-9-github'
  tfStateKey:            'hub-uks.tfstate'
  terraformVersion:      'latest'
