# .github/workflows/2-apply.yml

name: 2-apply

on:
  workflow_dispatch:
    inputs:
      fullEnvironment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - hub-uks
          - dev-uks
          - tst-uks
          - prd-uks

permissions:
  id-token: write
  contents: read

jobs:

  ##########
  ## PLAN ##
  ##########
  plan:

    name: ${{ inputs.fullEnvironment }}_plan

    runs-on:
      group: ai-hub-runners
      labels: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment Variables
        uses: ./.github/actions/load-environment
        with:
          fullEnvironment: ${{ inputs.fullEnvironment }}

      - name: Plan
        uses: ./.github/actions/plan

  ##############
  ## APPROVAL ##
  ##############
  approval:

    name: ${{ inputs.fullEnvironment }}_approval

    needs: plan

    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.fullEnvironment }}

    steps:

      - name: Approval Complete
        run: |
          echo "***** Approval Complete *****"

  ###########
  ## APPLY ##
  ###########
  apply:

    name: ${{ inputs.fullEnvironment }}_apply

    needs: approval

    runs-on:
      group: ai-hub-runners
      labels: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment Variables
        uses: ./.github/actions/load-environment
        with:
          fullEnvironment: ${{ inputs.fullEnvironment }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.tfEnvironment }}-${{ env.tfRegion }}-tfplan

      - name: Download Plan Changed Flag
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.tfEnvironment }}-${{ env.tfRegion }}-planChanged

      - name: Download Terraform Lock File
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.tfEnvironment }}-${{ env.tfRegion }}-terraform-lock-file

      - name: Apply
        uses: ./.github/actions/apply
